export const Capitais = [
  // { capital: "Rio Branco" }, 
  // { capital: "Maceió" },
  // { capital: "Macapá" },
  // { capital: "Manaus" },
  // { capital: "Salvador" },
  // { capital: "Fortaleza" },
  { capital: "Brasília" },
  // { capital: "Vitória" },
  // { capital: "Goiânia" },
  // { capital: "São Luíz" },
  { capital: "Belo Horizonte" },
  // { capital: "Belém" },
  // { capital: "João Pessoa" },
  { capital: "Curitiba" },
  { capital: "Recife" },
  { capital: "Teresina" },
  { capital: "Rio de Janeiro" },
  { capital: "Natal" },
  { capital: "Porto Alegre " },
  { capital: "Porto Velho" },
  { capital: "São Paulo" }
];